train_dataset:
  name:
  - 'ukbb_ecg'
  split: 'train'
  shuffle_size: 1024
  batch_size: 32
val_dataset:
  name:
  - 'ukbb_ecg'
  split: 'test'
  shuffle_size: 1024
  batch_size: 128


save_results_path: /users/wadh6616/VAE_ECG/results/overnight_trial2/
seed: 42
epochs: 400
latent_dimension: 8
learning_rate: 0.005
coefficients:
  alpha: 1.0
  beta: 4.0
  gamma: 1.0
coefficients_raise: 80
early_stopping: 100
reconstruction:
  period_plot: 20
  index_sample: 5
